# Default settings
[settings]
fullscreen = true
syncplay = false
discord_presence = false
language = [
    "DE",
    "EN",
    "EN_DESUB",
    "JP_DESUB",
    "JP_ENSUB"
]
hoster = [
    "ST",
    "VEO",
    "VZ",
    "DS"
]
update_checker = true

[settings.ani_skip]
skip_opening = false
skip_ending = false
chapters = false

[settings.player]
player = "AutomaticPlayer"
#path = ""
#args = ["--idk", "--owo"]

[settings.autoplay]
enabled = true
#time = 3

[settings.providers]
aniworld_to = true
serienstream_to = false

[meta]
version = "0.0.0"
